services:
  wordle-bot:
    build: .
    container_name: wordle-bot
    restart: unless-stopped
    networks:
      - traefik
    labels: #Literary no fucking idea how this works, copied straight from the playbook generated rules, substituting
      - "traefik.enable=true"
      - "traefik.http.routers.wordle.rule=Host(`wordle.simplybush.pl`)" # here by adding the wordle prefix
      - "traefik.http.routers.wordle.entrypoints=web-secure"
      - "traefik.http.routers.wordle.tls=true"
      - "traefik.http.routers.wordle.tls.certresolver=default"
      - "traefik.http.services.wordle.loadbalancer.server.port=3000" # and here by changing the port
    volumes:
      - ./data:/app/data

networks:
  traefik:
    external: true